name: salaah
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.1
  intl: ^0.19.0
  confetti: ^0.8.0
  google_fonts: ^6.2.1

#  لي اضافه اللغه العربيه داخل التطبيق
dev_dependencies:
  flutter_test:
    sdk: flutter
    #   ده خاص بان التطبيق يكون عربي 
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700